# This workflow is deprecated. Use ./update-snapshots.yml instead.
#
# This workflow will be deleted once the replacement has been stabilized.
name: Old update snapshots

on:
  # Run any time when a new label added to the PR
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

# cancel workflow when a newer version of the workflow is triggered on the same github ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # get matrix for ci-jobs
  get_matrix:
    name: Set CI flavors
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Ensure node version is great enough
      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # gets the matrix for ci run from the config file
      - id: get-matrix
        run: echo "::set-output name=matrix::$(node ./common/scripts/workflow-read-matrix.mjs)"

  update_examples_snapshot:
    needs: get_matrix
    name: Update component examples snapshot by label
    # This job will only run if the comment was on a pull requests and matches the label
    if: ${{ github.event.label.name == 'ui change' || contains( github.event.pull_request.labels.*.name, 'ui change') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get_matrix.outputs.matrix) }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Use a machine account when checking out. This is to workaround the issue were GitHub
          # actions, when using the default account, cannot trigger other actions.
          # This machine account is only for this PAT, pwd was created and thrown away
          # If any update needed, create a new account, add access to the repo and generate a new PAT
          token: ${{ secrets.MACHINE_ACCOUNT_PAT }}
      # Setup bot information for pushing new changes
      # Here we use the id from the github actions bot: https://api.github.com/users/better-informatics%5Bbot%5D
      - name: Setup bot git information
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: If run on a PR, merge base branch to get existing snapshot updates
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge ${{ env.GITHUB_BASE_REF }}

      # Ensure node version is great enough
      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # Try get node_modules from cache
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      # Install dependencies
      - name: Install rush
        run: npm install -g @microsoft/rush@5.47.0
      - name: Install dependencies
        run: rush install
      # Switch flavor when necessary
      - name: Switch flavor for stable build
        if: ${{ matrix.flavor == 'stable' }}
        run: rush switch-flavor:stable
      - name: Build Packages
        run: rush build -t @azure/communication-react
      - name: Build
        run: rush build -t component-examples
      - name: Update snapshot
        id: updatesnapshots
        run: |
          cd samples/tests
          rushx update:snapshot:examples
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      - name: Upload snapshot diff
        if: ${{ always() && steps.updatesnapshots.outcome == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: snapshots
          path: samples/tests/test-results
      # Check if files have changed
      # More information see: https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes
      - name: Check for snapshot changes
        id: changescheck
        run: |
          if [[ -z $(git status samples/tests -s) ]]
          then
            echo "::set-output name=hasChanged::false"
          else
            echo "::set-output name=hasChanged::true"
            exit
          fi
      - name: Commit new snapshots
        if: ${{ steps.changescheck.outputs.hasChanged == 'true' }}
        run: |
          git add samples/tests/*.png
          git commit -m 'Update js bundle automation snapshots'
          git push

  update_bundle_snapshot:
    needs: get_matrix
    name: Update embed html bundle snapshot by label
    # This job will only run if the comment was on a pull requests and matches the label
    if: ${{ github.event.label.name == 'ui change' || contains( github.event.pull_request.labels.*.name, 'ui change') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get_matrix.outputs.matrix) }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Use a machine account when checking out. This is to workaround the issue were GitHub
          # actions, when using the default account, cannot trigger other actions.
          # This machine account is only for this PAT, pwd was created and thrown away
          # If any update needed, create a new account, add access to the repo and generate a new PAT
          token: ${{ secrets.MACHINE_ACCOUNT_PAT }}
      # Setup bot information for pushing new changes
      # Here we use the id from the github actions bot: https://api.github.com/users/better-informatics%5Bbot%5D
      - name: Setup bot git information
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: If run on a PR, merge base branch to get existing snapshot updates
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge ${{ env.GITHUB_BASE_REF }}

      # Ensure node version is great enough
      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # Try get node_modules from cache
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      # Install dependencies
      - name: Install rush
        run: npm install -g @microsoft/rush@5.47.0
      - name: Install dependencies
        run: rush install
      # Switch flavor when necessary
      - name: Switch flavor for stable build
        if: ${{ matrix.flavor == 'stable' }}
        run: rush switch-flavor:stable
      - name: Build Packages
        run: rush build -t @azure/communication-react
      - name: Build
        run: rush build -t sample-static-html-composites
      - name: Update snapshot
        id: updatesnapshots
        run: |
          cd samples/tests
          rushx update:snapshot:bundle
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      - name: Upload snapshot diff
        if: ${{ always() && steps.updatesnapshots.outcome == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: snapshots
          path: samples/tests/test-results
      # Check if files have changed
      # More information see: https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes
      - name: Check for snapshot changes
        id: changescheck
        run: |
          if [[ -z $(git status samples/tests -s) ]]
          then
            echo "::set-output name=hasChanged::false"
          else
            echo "::set-output name=hasChanged::true"
            exit
          fi
      - name: Commit new snapshots
        if: ${{ steps.changescheck.outputs.hasChanged == 'true' }}
        run: |
          git add samples/tests/*.png
          git commit -m 'Update js bundle automation snapshots'
          git push

  update_composite_snapshot:
    needs: get_matrix
    name: Update composite snapshot by label
    # This job will only run if the comment was on a pull requests and matches the label
    if: ${{ github.event.label.name == 'ui change' || contains( github.event.pull_request.labels.*.name, 'ui change') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get_matrix.outputs.matrix) }}
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Use a machine account when checking out. This is to workaround the issue were GitHub
          # actions, when using the default account, cannot trigger other actions.
          # This machine account is only for this PAT, pwd was created and thrown away
          # If any update needed, create a new account, add access to the repo and generate a new PAT
          token: ${{ secrets.MACHINE_ACCOUNT_PAT }}
      # Setup bot information for pushing new changes
      # Here we use the id from the github actions bot: https://api.github.com/users/better-informatics%5Bbot%5D
      - name: Setup bot git information
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: If run on a PR, merge base branch to get existing snapshot updates
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge ${{ env.GITHUB_BASE_REF }}

      # Ensure node version is great enough
      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      - name: Install rush
        run: npm install -g @microsoft/rush@5.47.0
      - name: Install dependencies
        run: rush install
      - name: Switch flavor for stable build
        if: ${{ matrix.flavor == 'stable' }}
        run: rush switch-flavor:stable
      - name: Build Test
        working-directory: ./packages/react-composites
        run: rushx build:e2e
      - name: Install packlets used by browser tests
        run: |
          cd packages/react-composites
          rush build -t .
      - name: Update chat snapshot
        id: update-chat-snapshots
        run: rushx test:e2e:chat:update
        working-directory: ./packages/react-composites
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      - name: Update calling snapshot
        id: update-calling-snapshots
        run: rushx test:e2e:call:update
        working-directory: ./packages/react-composites
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      - name: Update call with chat snapshot
        id: update-call-with-chat-snapshots
        run: rushx test:e2e:callwithchat:update
        working-directory: ./packages/react-composites
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      - name: Upload snapshot diff
        if: ${{ always() && steps.updatesnapshots.outcome == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: snapshots
          path: packages/react-composites/test-results
      # Check if files have changed
      # More information see: https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes
      - name: Check for snapshot changes
        id: changescheck
        run: |
          if [[ -z $(git status packages -s) ]]
          then
            echo "::set-output name=hasChanged::false"
          else
            echo "::set-output name=hasChanged::true"
          fi
      - name: Commit new snapshots
        if: ${{ steps.changescheck.outputs.hasChanged == 'true' }}
        run: |
          git add packages/react-composites/*.png
          git commit -m 'Update composite automation snapshots'
          git push
