name: Release

on:
  release:
    name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v2

      # Ensure node version is great enough
      - name: Use Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install dependencies
      - name: Install rush
        run: npm install -g @microsoft/rush
      - name: Install dependencies
        run: rush install

      # Builds
      - name: Build Packages and Samples
        run: rush build

      # Generate Chat build
      - name: Generate Chat build
        run: npm run package
        working-directory: ./samples/Chat
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      # Package Chat build
      - name: Package Chat build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name=Chat-$tag
          unset CI
          7z a -tzip "${release_name}.zip" "./dist/*"
        working-directory: ./samples/Chat
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'Chat-*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate Calling build
      - name: Generate Calling build
        run: npm run package
        working-directory: ./samples/Calling
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

      # Package Calling build
      - name: Package Calling build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name=Calling-$tag
          unset CI
          7z a -tzip "${release_name}.zip" "./dist/*"
        working-directory: ./samples/Calling
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'Calling-*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
